/* Main.c file generated by New Project wizard
 *
 * Author:	  Tushar Gupta
 * Created:   Sat May 7 2022
 * Processor: 80C31
 * Compiler:  Keil for 8051
 */

#include <reg51.h>
#include <stdio.h>

#define bit_setter(x,y,z) \
z?(x |= (1<<y)):(x &= ~(1<<y))

#define sec_1 15624
#define ms_20 310

void delay_ms(long int wait)
{
	long int i = 0;
	while(i < wait)
	{
		TMOD = 0x01;
		TH0 = 0xFF;
		TL0 = 0xFF;
		TCON = 0x10;	//00010000
		while(TF0==0);
		TCON = 0x00;
		i++;
	}
}

void sendCmd(unsigned char bitt, unsigned char cmd)
{

	P2 &= ~( 1 << 2 );	// RS LOW
	P2 &= ~( 1 << 1 );	// RW LOW

	if(bitt == 8)
	{

		P1 = cmd;

		// sending enable pulse
		P2 |= ( 1 << 0 );
		delay_ms(1500);	// 1500 gives approx delay of 100 miliseconds
		P2 &= ~( 1 << 0 );
	}
	else
	{
		unsigned char temp;
		// sending upper nibble
		temp = cmd & 0xF0;
		P1 &= 0x0F;
		P1 |= temp; 
		// sending enable pulse
		P2 |= ( 1 << 0 );
		delay_ms(1500);
		P2 &= ~( 1 << 0 );

		//sending lower nibble
		cmd = (cmd << 4) & 0xF0;
		P1 &= 0x0F;
		P1 |= cmd; 
		// sending enable pulse
		P2 |= ( 1 << 0 );
		delay_ms(1500);
		P2 &= ~( 1 << 0 );
	}

}

void sendData(unsigned char bitt,unsigned char dataa)
{
	P2 |= ( 1 << 2 );
	P2 &= ~( 1 << 1 );

	if (bitt == 8)
	{
		P1 = dataa;
		
		// sending enable pulse
		P2 |= ( 1 << 0 );
		delay_ms(1500);
		P2 &= ~( 1 << 0 );
	}

	else
	{
		unsigned char temp;
		// sending upper nibble
		temp = dataa & 0xF0;
		P1 &= 0x0F;
		P1 |= temp; 
		// sending enable pulse
		P2 |= ( 1 << 0 );
		delay_ms(1500);
		P2 &= ~( 1 << 0 );

		//sending lower nibble
		dataa = (dataa << 4) & 0xF0;
		P1 &= 0x0F;
		P1 |= dataa; 
		// sending enable pulse
		P2 |= ( 1 << 0 );
		delay_ms(1500);
		P2 &= ~( 1 << 0 );
	}
}

void initLcd(unsigned char bitt)
{
	delay_ms(ms_20);	// lcd takes approx. 15 ms to startup
	if (bitt == 8)
		sendCmd(bitt, 0x38);	// 8-bit bit mode
	else
		sendCmd(bitt, 0x28);	// 4-bit bit mode
	sendCmd(bitt, 0x06);	// entry mode
	sendCmd(bitt, 0x01);	// clear display
	sendCmd(bitt, 0x02);	// return home
	sendCmd(bitt, 0x0C);	// display ON cursor OFF
	//sendCmd(bitt, 0x80);
	
}

int main(void)
 { 
	unsigned char message[] = "put any message here";
	unsigned char bitt = 8;
	int i;

	initLcd(bitt);
	sendData(bitt, 0x41);
	for(i=0;message[i] != '\0';i++)
	{
		if(i == 16)
			sendCmd(bitt, 0xC0);
		sendData(bitt, message[i]);
	}
	while(1);
	return 0;
 }
